version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --no-cache -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...$AWS_ACCOUNT_ID....$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "[{\"name\":\"${CONTAINAR_NAME}\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\",\"environment\":[{\"name\":\"TWITTER_ACCESS_TOKEN\",\"value\":\"${TWITTER_ACCESS_TOKEN}\"},{\"name\":\"TWITTER_ACCESS_TOKEN_SECRET\",\"value\":\"${TWITTER_ACCESS_TOKEN_SECRET}\"},{\"name\":\"TWITTER_CONSUMER_KEY\",\"value\":\"${TWITTER_CONSUMER_KEY}\"},{\"name\":\"TWITTER_CONSUMER_SECRET\",\"value\":\"${TWITTER_CONSUMER_SECRET}\"},{\"name\":\"BITLY_TOKEN\",\"value\":\"672116007daee10d4f16dd31315b6e9941173df5\"}]}]" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
  