version: '3'
services:
  api:
    environment:
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
      TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
      TWITTER_ACCESS_TOKEN_SECRET: $TWITTER_ACCESS_TOKEN_SECRET
    build: .
    command: go run main.go 
    volumes:
      - .:/hellogo 
    ports:
      - 8080:8080